### ISSUE TITLE
Saving a worksheet gives rise to the error: TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by FreddyBaudine** [Mathics3/mathics-django#20] opened 2021-02-16 17:27 UTC
Hi Mauricio,

Following up on your request, I am reporting here the following mishap which happened on my system, Windows 7 Professional, Service Pack 1, 64-bit.

After launching mathicsserver.
I wanted to test how 'saving worksheet' and 'openworksheet' worked.
Alas, no saving took place and I got the following error: TypeError: 'bool' object is not callable
All the details are in the dump below.

`C:\Users\Freddy\Desktop\Mathics\Mathics3>C:\Users\Freddy\AppData\Local\Programs\Python\Python38\Scripts\mathic
sserver.exe
Migrating database C:/Users/Freddy/AppData/Roaming/Python/Mathics/mathics.sqlite
Operations to perform:
Apply all migrations: auth, contenttypes, sessions, sites, web
Running migrations:
No migrations to apply.

database initialized sucessfully

Django front end version 2.0.1.dev
Mathics 2.0.0
on CPython 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
using SymPy 1.7.1, mpmath 1.1.0, django 3.1.6

Copyright (C) 2011-2021 The Mathics Team.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
See the documentation for the full license.

Quit by pressing CTRL-BREAK

Open the graphical user interface at
http://localhost:8000
in Firefox, Chrome, or Safari to use Mathics

[16/Feb/2021 16:42:19] "GET / HTTP/1.1" 200 9771
[16/Feb/2021 16:42:58] "POST /ajax/query/ HTTP/1.1" 200 371
[16/Feb/2021 16:42:58] "GET /media/js/mathjax/jax/output/HTML-CSS/fonts/TeX/SansSerif/Regular/Other.js HTTP/1.
1" 304 0
[16/Feb/2021 16:43:09] "GET /ajax/doc/ HTTP/1.1" 200 7044
Internal Server Error: /ajax/save/
Traceback (most recent call last):
File "c:\users\freddy\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exceptio
n.py", line 47, in inner
response = get_response(request)
File "c:\users\freddy\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py"
, line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "c:\users\freddy\mathics-django\mathics_django\web\views.py", line 287, in save
if not user.is_authenticated():
TypeError: 'bool' object is not callable
[16/Feb/2021 16:46:39] "POST /ajax/save/ HTTP/1.1" 500 70126`

Regards,
Freddy

**Comment by rocky** [comment] 2021-02-16 18:01
Is this a duplicate of https://github.com/Mathics3/mathics-django/issues/12  ?

**Comment by mmatera** [comment] 2021-02-16 19:13
> Is this a duplicate of #12 ?

Seems related, and maybe have the same root...

**Closed** 2021-02-20 01:16 UTC

**Comment by FreddyBaudine** [comment] 2021-02-20 07:14
Hi Rocky,
I know work is in progress but I thought you'd like to known that saving a worksheet works alright. You're even asked if you want to overwrite any existing worksheet.
However, when you try to open the saved file, the same error as before is issued: TypeError: 'bool' object is not callable.
Here's the dump:
'
[20/Feb/2021 08:11:05] "GET / HTTP/1.1" 200 9771
Internal Server Error: /ajax/getworksheets/
Traceback (most recent call last):
  File "c:\users\freddy\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\exceptio
n.py", line 47, in inner response = get_response(request)
  File "c:\users\freddy\appdata\local\programs\python\python38\lib\site-packages\django\core\handlers\base.py"
, line 181, in _get_response  response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\users\freddy\mathics-django\mathics_django\web\views.py", line 335, in get_worksheets
    if request.user.is_authenticated(): TypeError: 'bool' object is not callable
[20/Feb/2021 08:11:14] "GET /ajax/getworksheets/ HTTP/1.1" 500 67412
'
Regards,
Freddy

**Comment by rocky** [comment] 2021-02-20 11:24
Should be addressed by 17f80abbccd729545f8e56420930f58454f43d8b

**Comment by FreddyBaudine** [comment] 2021-02-20 14:10
Many thanks Rocky, it works both ways now.
Regards,
Freddy
