### ISSUE TITLE
DensityPlot is not shown anymore.

### ISSUE THREAD

**Issue by mmatera** [Mathics3/mathics-django#75] opened 2021-06-13 14:05 UTC
This function seems to pass the tests in Mathics core, but it is not shown in the browser anymore.

```
mathics -e 'DensityPlot[x ^ 2 + 1 / y, {x, -1, 1}, {y, 1, 4}]//MathMLForm'  
```
produces
```
<math display="block"><mglyph width="350px" height="350px" src="data:image/svg+xml;base64,PHN ..."></mathml>
```
but it seems that it is not processed by the frontend.

**Comment by TiagoCavalcanteTrindade** [comment] 2021-06-13 17:03
@mmatera and @rocky this is a problem in Mathics Core.

This is a part of the value passed to the function `createLine`:
```html
<polygon points="0.000000,300.000000 50.000000,350.000000 50.000000,300.000000"
           fill-rule="evenodd"
           style="stroke: none; stroke-width: 0.000000px; fill: none; opacity: 1.0" />
<polygon points="0.000000,300.000000 0.000000,250.000000 50.000000,300.000000"
           fill-rule="evenodd"
           style="stroke: none; stroke-width: 0.000000px; fill: none; opacity: 1.0" />
<polygon points="0.000000,250.000000 50.000000,300.000000 50.000000,250.000000"
           fill-rule="evenodd"
           style="stroke: none; stroke-width: 0.000000px; fill: none; opacity: 1.0" />
```

As you can see `fill` is always none, if you change it to a color it works.

![gif](https://user-images.githubusercontent.com/62714153/121816104-064b9a00-cc50-11eb-91bf-c15eee113bb9.gif)

**Comment by rocky** [comment] 2021-06-13 17:16
There is something more to it than just this because the code that sets that [has been around for a while](https://github.com/mathics/Mathics/blob/2.2.0/mathics/builtin/graphics.py#L133-L138), just in a different place.

What is different is that this used to be in a math tag, and now it isn't. I am guessing that the math tag filled in a color when it was set to none here? 

We could easily change this, but where should we get the fill value from.  What was it set to in Mathics 2.2.0?

**Comment by TiagoCavalcanteTrindade** [comment] 2021-06-13 17:23
@rocky I switched to an older version (e903defcc5065685bbbbb33a3b8b8e77bcd51c2c) and it is also none.

**Comment by rocky** [comment] 2021-06-13 17:32
@TiagoCavalcanteTrindade Thanks for the information. 

Do we know though what the fill color should be and where we should get that? If so, I think this is easily addressed.

**Comment by TiagoCavalcanteTrindade** [comment] 2021-06-13 17:36
Maybe the problem is [here](https://github.com/mathics/Mathics/blob/master/mathics/formatter/svg.py#L289-L318).

**Comment by TiagoCavalcanteTrindade** [comment] 2021-06-13 17:40
@rocky I found out in that function `self.face_color` is all black or None (I changed line 291 to `if True:` and I get a black SVG.

**Comment by TiagoCavalcanteTrindade** [comment] 2021-06-13 17:54
@rocky the `self.face_color` of `PolygonBox` is black.

**Comment by rocky** [comment] 2021-06-13 18:02
I am running in the kind of old code that wasn't well commented and I have no idea what's going on. Why it used to work and now why it doesn't. 

In particular there is this: 

```
    if self.vertex_colors is None:
        face_color = self.face_color
    else:
        face_color = None
    style = create_css(
        edge_color=self.edge_color, face_color=face_color, stroke_width=line_width
    )
```

This code is virtually unchanged from 2.2.0. That is a mystery is how `self.vertex_colors` is related to `self.face_color` and why if `self.vertex_colors` is not set then we should use face_color None, but if it is set we set it to be face_color.

Sure, we can change this to something else. But it would be nice to understand what was going on and why.

**Comment by TiagoCavalcanteTrindade** [comment] 2021-06-13 18:08
@rocky yes it'd be nice, to me it also doesn't makes sense.

**Comment by rocky** [comment] 2021-06-13 18:11
Ok. Here is a start of understanding what's up. I think face_color None means that things are transparent. So the presumption is that if there are vertex colors then those fill should be removed and the vertex colors will do the trick.

There is a loop below that is dumping the meshgradient data.

**Comment by rocky** [comment] 2021-06-13 18:31
So now my guess of what's going on is that SVG just isn't rendering right for meshgradientdata. 

At first I had thought maybe my changing the the polygonbox  fillrule to "evenodd" might have caused this. (even odd is the rule we should be using to follow WL). 

However when I remove that, same problem. 

I'll mention one other thing that I hope will be instructive....

In the document examples we still don't use SVG but have MathML embedding.  This is because at the top level we have a document certain boxes in that are Graphics of some kind.

This information comes from a pickled file and even the images start out cached. To regenerate the all of  images this command can be used: 

```
python mathics_django/docpipeline.py -o
```

however this takes a long time. So I recently added some options to allow regeneration of a particular section: 

```
python mathics_django/docpipeline.py -o --reload -s DensityPlot
```

Lastly, I'll say with respect to this bug is that, we've seen this kind of thing happen before. Raster imaging has been broken for a while. In general though I'd prefer to have the code more under control than having things be in a state that no one understands and is difficult to debug (because images have been base encoded and then in Django hidden from view.)

I suspect fixing this bug will mean understand what's up with Density Plot if if we document what that is, down the line we will be in a better shape than we are or were.

**Comment by rocky** [comment] 2021-06-13 18:45
@TiagoCavalcanteTrindade I now think this _is_  mathics django  related than I had thought before. 

We now get an SVG like...

````
<svg width="351.33333333333337px" height="351.33333333333337px" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="-0.666667 -0.666667 351.333333 351.333333">
                <meshgradient data="[[[[0.0, 350.0], [0.941176, 0.906538, 0.834043]], [[0.0, 300.0], [0.8482693982300884, 0.8755561238938052, 0.8756650743362833]], [[50.0, 350.0], [0.7894917522123893, 0.8559553451327434, ...
```

The think to note is that this _isn't_ value SVG.

There seems to be code in `mathics.js`  https://github.com/Mathics3/mathics-django/blob/master/mathics_django/web/media/js/mathics.js#L96 specifically for meshdata

**Comment by rocky** [comment] 2021-06-13 18:53
If it is possible to fix this by producing valid SVG inside mathics core, that would be nice. And reduce confusion.

**Comment by TiagoCavalcanteTrindade** [comment] 2021-06-13 18:55
@rocky I checked an old version of Mathics Django and I found the following: `nodeName == 'meshgradient'`, there's code for converting `meshgradient`.

> If it is possible to fix this by producing valid SVG inside mathics core, that would be nice. And reduce confusion.

Yes.

**Comment by rocky** [comment] 2021-06-13 19:14
In 9235d2a3 I added a few comments about SVG's polygonbox

**Comment by rocky** [comment] 2021-06-13 20:46
@TiagoCavalcanteTrindade I've been looking at this. Here is a suggestion for how to redo. 

First, I don't think we should try to shoehorn this into a PolygonBox  as collection of triangles but instead do this as its own DensityPlotBox which has its own SVG formatter in `svg.py`  (and asy.py)

In the SVG implementation a [Radial Gradient](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients#radial_gradient) is probably best. 

My take this that if this is something that interests you and you wan to take time to get this right, there is no rush on it. 

What do you think? 

@mmatera your thoughts?

**Comment by TiagoCavalcanteTrindade** [comment] 2021-06-13 21:34
@rocky earlier today I searched about `<meshgradient />` on Google and nothing, now I searched about `<radialgradient />` and the first result is Mozilla documentation, so I'm with you.

**Comment by rocky** [comment] 2021-06-14 07:03
@TiagoCavalcanteTrindade in order to get things start in DensityPlot, I created in Mathics branch https://github.com/mathics/Mathics/tree/add-density-plot-box 

The formatting code in `svg.py` and `asy.py` is pretty much blank and needs to be fixed.  I was largely focusing on adding the DensityPlotBox so that these routines could get called. And even that is a little more messy than I would have expected. 

There may be some changes needed there or values to be filled in like the vertex colors of the density plot. (Even if we start off with some canned set, and expand that later, this is preferrable). 

I would offer you an invite to be able to commit to Mathics core, but I see that I don't have permission to do that. 

At this point, I am okay with moving Mathics over to the Mathics3 organization where I can do this and rename it to Mathics-Core which is now what this should be becoming. In the old days all of the components that are now in Mathics3 were in that one little (in terms of functionality, but big in terms of code size) project.

**Comment by TiagoCavalcanteTrindade** [comment] 2021-06-14 10:51
@rocky about moving the repository of Mathics Core, I think this will reduce the confusion.

**Comment by rocky** [comment] 2021-07-18 23:42
We have something here now (even if kind of minimal). But at any rate this is a Mathics core problem not a Mathics Django problem.

**Closed by rocky** 2021-07-18 23:42 UTC
